version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: telegram_pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  fastapi:
    build: .
    container_name: telegram_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - SESSION_NAME=${SESSION_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata:
