name: telegram_data_pipeline
version: '1.0'
config-version: 2

profile: telegram_pipeline

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  telegram_data_pipeline:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: view
