version: 2

models:
  - name: stg_messages
    description: |
      Staging model for messages extracted from raw Telegram data, representing communication in Ethiopian medical business channels.
      This model cleans and structures raw JSON data for downstream analytics, such as identifying trending medical products.
    config:
      materialized: table
      schema: staging
    columns:
      - name: message_id
        description: "Unique identifier for each Telegram message."
        data_type: bigint
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Identifier of the user who sent the message, linking to the stg_users model."
        data_type: bigint
        tests:
          - not_null
      - name: message_text
        description: "Content of the message, used for extracting medical product mentions."
        data_type: text
        tests:
          - not_null
          - dbt_utils.not_empty_string
          - custom_message_length:
              max_length: 5000
              severity: warn
      - name: timestamp
        description: "Timestamp when the message was sent, used for temporal analysis of trends."
        data_type: timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

  - name: stg_users
    description: |
      Staging model for user data extracted from Telegram channels, capturing user information for medical business analysis.
      Used to track user engagement and channel activity.
    config:
      materialized: table
      schema: staging
    columns:
      - name: user_id
        description: "Unique identifier for each Telegram user."
        data_type: bigint
        tests:
          - not_null
          - unique
      - name: username
        description: "Telegram username of the user, if available."
        data_type: varchar(100)
        tests:
          - dbt_utils.accepted_values:
              values: ['not_null', '']
              quote: true
      - name: joined_at
        description: "Timestamp when the user joined the channel, used for engagement analysis."
        data_type: timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

tests:
  - name: custom_message_length
    description: "Custom test to ensure message_text length does not exceed max_length."
    query: |
      SELECT message_id
      FROM {{ ref('stg_messages') }}
      WHERE LENGTH(message_text) > {{ max_length }}
    severity: "{{ severity }}"